-- Kingxford organization collaboration controls.
-- Invitation secrets are generated by the application and only SHA-256
-- digests enter Postgres. All mutations are authenticated, tenant-bound,
-- idempotent, audited, and executed through the guarded functions below.

create table if not exists public.organization_invitations (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  email text not null check (
    email = lower(trim(email))
    and char_length(email) between 3 and 254
    and email ~ '^[^ @]+@[^ @]+\.[^ @]+$'
  ),
  role public.organization_role not null check (role in ('editor', 'reviewer', 'viewer')),
  token_hash text not null unique check (token_hash ~ '^[0-9a-f]{64}$'),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  accepted_by uuid references auth.users(id) on delete set null,
  accepted_at timestamptz,
  revoked_by uuid references auth.users(id) on delete set null,
  revoked_at timestamptz,
  check (expires_at > created_at and expires_at <= created_at + interval '7 days'),
  check ((accepted_at is null) = (accepted_by is null)),
  check ((revoked_at is null) = (revoked_by is null)),
  check (accepted_at is null or revoked_at is null)
);

create index if not exists organization_invitations_pending_idx
  on public.organization_invitations(organization_id, expires_at)
  where accepted_at is null and revoked_at is null;
create index if not exists organization_invitations_email_idx
  on public.organization_invitations(organization_id, email, created_at desc);

alter table public.organization_invitations enable row level security;

drop policy if exists organization_invitations_select_admin on public.organization_invitations;
create policy organization_invitations_select_admin on public.organization_invitations
for select to authenticated
using (
  public.has_organization_role(
    organization_id,
    array['owner', 'admin']::public.organization_role[]
  )
);

revoke all on public.organization_invitations from authenticated;

create or replace function public.list_kingxford_organizations()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', organization.id,
        'name', organization.name,
        'slug', organization.slug,
        'role', membership.role,
        'joinedAt', membership.joined_at
      )
      order by membership.joined_at, organization.id
    ),
    '[]'::jsonb
  )
  from public.organization_members membership
  join public.organizations organization on organization.id = membership.organization_id
  where membership.user_id = auth.uid();
$$;

revoke all on function public.list_kingxford_organizations() from public;
grant execute on function public.list_kingxford_organizations() to authenticated;

create or replace function public.get_kingxford_organization_access(
  p_organization_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_actor_role public.organization_role;
  v_can_manage boolean;
  v_organization jsonb;
  v_members jsonb;
  v_invitations jsonb;
begin
  if v_user_id is null then
    raise sqlstate 'KX401' using message = 'Authentication required';
  end if;

  select membership.role into v_actor_role
  from public.organization_members membership
  where membership.organization_id = p_organization_id
    and membership.user_id = v_user_id;
  if v_actor_role is null then
    raise sqlstate 'KX403' using message = 'Organization access denied';
  end if;
  v_can_manage := v_actor_role in ('owner', 'admin');

  select jsonb_build_object(
    'id', organization.id,
    'name', organization.name,
    'slug', organization.slug
  ) into v_organization
  from public.organizations organization
  where organization.id = p_organization_id;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'userId', membership.user_id,
        'email', user_record.email,
        'role', membership.role,
        'joinedAt', membership.joined_at,
        'isCurrentUser', membership.user_id = v_user_id
      )
      order by
        case membership.role
          when 'owner' then 1
          when 'admin' then 2
          when 'editor' then 3
          when 'reviewer' then 4
          else 5
        end,
        membership.joined_at,
        membership.user_id
    ),
    '[]'::jsonb
  ) into v_members
  from public.organization_members membership
  left join auth.users user_record on user_record.id = membership.user_id
  where membership.organization_id = p_organization_id
    and (v_can_manage or membership.user_id = v_user_id);

  if v_can_manage then
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id', invitation.id,
          'email', invitation.email,
          'role', invitation.role,
          'createdAt', invitation.created_at,
          'expiresAt', invitation.expires_at
        ) order by invitation.created_at desc, invitation.id
      ),
      '[]'::jsonb
    ) into v_invitations
    from public.organization_invitations invitation
    where invitation.organization_id = p_organization_id
      and invitation.accepted_at is null
      and invitation.revoked_at is null
      and invitation.expires_at > now();
  else
    v_invitations := '[]'::jsonb;
  end if;

  return jsonb_build_object(
    'organization', v_organization,
    'actorRole', v_actor_role,
    'canManage', v_can_manage,
    'members', v_members,
    'invitations', v_invitations
  );
end;
$$;

revoke all on function public.get_kingxford_organization_access(uuid) from public;
grant execute on function public.get_kingxford_organization_access(uuid) to authenticated;

create or replace function public.create_kingxford_organization_invitation(
  p_organization_id uuid,
  p_email text,
  p_role public.organization_role,
  p_expires_at timestamptz,
  p_token_hash text,
  p_idempotency_key text,
  p_request_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_operation constant text := 'organization.invitation.create';
  v_previous public.idempotency_keys%rowtype;
  v_invitation_id uuid;
  v_response jsonb;
  v_now timestamptz := now();
  v_active_count bigint;
begin
  if v_user_id is null then
    raise sqlstate 'KX401' using message = 'Authentication required';
  end if;
  if not public.has_organization_role(
    p_organization_id,
    array['owner', 'admin']::public.organization_role[],
    v_user_id
  ) then
    raise sqlstate 'KX403' using message = 'Only organization owners and administrators can create invitations';
  end if;
  if p_email <> lower(trim(p_email))
    or char_length(p_email) not between 3 and 254
    or p_email !~ '^[^ @]+@[^ @]+\.[^ @]+$'
    or p_role is null
    or p_role not in ('editor', 'reviewer', 'viewer')
    or p_expires_at <= v_now
    or p_expires_at > v_now + interval '7 days'
    or p_token_hash !~ '^[0-9a-f]{64}$'
    or char_length(p_idempotency_key) not between 8 and 160
    or p_request_hash !~ '^kxhash_[0-9a-f]{32}$' then
    raise sqlstate 'KX400' using message = 'Invalid invitation request';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      p_organization_id::text || ':' || v_user_id::text || ':' || p_idempotency_key,
      0
    )
  );
  select * into v_previous
  from public.idempotency_keys key_record
  where key_record.organization_id = p_organization_id
    and key_record.user_id = v_user_id
    and key_record.key = p_idempotency_key
  for update;
  if found then
    if v_previous.operation <> v_operation or v_previous.request_hash <> p_request_hash then
      raise sqlstate 'KX409' using message = 'Idempotency key conflict';
    end if;
    if v_previous.response_body is null then
      raise sqlstate 'KX409' using message = 'Invitation creation is still processing';
    end if;
    return v_previous.response_body || jsonb_build_object('replayed', true);
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_organization_id::text || ':invite:' || p_email, 0)
  );
  if exists (
    select 1
    from public.organization_members membership
    join auth.users user_record on user_record.id = membership.user_id
    where membership.organization_id = p_organization_id
      and lower(trim(user_record.email)) = p_email
  ) then
    raise sqlstate 'KX409' using message = 'This account is already a member of the organization';
  end if;

  select count(*) into v_active_count
  from public.organization_invitations invitation
  where invitation.organization_id = p_organization_id
    and invitation.email <> p_email
    and invitation.accepted_at is null
    and invitation.revoked_at is null
    and invitation.expires_at > v_now;
  if v_active_count >= 50 then
    raise sqlstate 'KX409' using message = 'The organization has reached its active invitation limit';
  end if;

  insert into public.idempotency_keys (
    organization_id, user_id, key, operation, request_hash
  ) values (
    p_organization_id, v_user_id, p_idempotency_key, v_operation, p_request_hash
  );

  update public.organization_invitations
  set revoked_at = v_now,
      revoked_by = v_user_id
  where organization_id = p_organization_id
    and email = p_email
    and accepted_at is null
    and revoked_at is null
    and expires_at > v_now;

  insert into public.organization_invitations (
    organization_id, email, role, token_hash, created_by, created_at, expires_at
  ) values (
    p_organization_id, p_email, p_role, p_token_hash, v_user_id, v_now, p_expires_at
  ) returning id into v_invitation_id;

  insert into public.audit_events (
    organization_id, actor_user_id, action, target_type, target_id,
    request_id, metadata, created_at
  ) values (
    p_organization_id, v_user_id, 'organization.invitation.created',
    'organization_invitation', v_invitation_id::text, p_idempotency_key,
    jsonb_build_object('role', p_role, 'expiresAt', p_expires_at), v_now
  );

  v_response := jsonb_build_object(
    'status', 'created',
    'invitationId', v_invitation_id,
    'email', p_email,
    'role', p_role,
    'expiresAt', p_expires_at,
    'replayed', false
  );
  update public.idempotency_keys
  set response_body = v_response, response_status = 201, completed_at = v_now
  where organization_id = p_organization_id
    and user_id = v_user_id
    and key = p_idempotency_key;
  return v_response;
end;
$$;

revoke all on function public.create_kingxford_organization_invitation(
  uuid, text, public.organization_role, timestamptz, text, text, text
) from public;
grant execute on function public.create_kingxford_organization_invitation(
  uuid, text, public.organization_role, timestamptz, text, text, text
) to authenticated;

create or replace function public.revoke_kingxford_organization_invitation(
  p_organization_id uuid,
  p_invitation_id uuid,
  p_idempotency_key text,
  p_request_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_operation constant text := 'organization.invitation.revoke';
  v_previous public.idempotency_keys%rowtype;
  v_invitation public.organization_invitations%rowtype;
  v_response jsonb;
  v_now timestamptz := now();
begin
  if v_user_id is null then
    raise sqlstate 'KX401' using message = 'Authentication required';
  end if;
  if not public.has_organization_role(
    p_organization_id,
    array['owner', 'admin']::public.organization_role[],
    v_user_id
  ) then
    raise sqlstate 'KX403' using message = 'Only organization owners and administrators can revoke invitations';
  end if;
  if char_length(p_idempotency_key) not between 8 and 160
    or p_request_hash !~ '^kxhash_[0-9a-f]{32}$' then
    raise sqlstate 'KX400' using message = 'Invalid invitation revocation';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      p_organization_id::text || ':' || v_user_id::text || ':' || p_idempotency_key,
      0
    )
  );
  select * into v_previous
  from public.idempotency_keys key_record
  where key_record.organization_id = p_organization_id
    and key_record.user_id = v_user_id
    and key_record.key = p_idempotency_key
  for update;
  if found then
    if v_previous.operation <> v_operation or v_previous.request_hash <> p_request_hash then
      raise sqlstate 'KX409' using message = 'Idempotency key conflict';
    end if;
    return v_previous.response_body || jsonb_build_object('replayed', true);
  end if;

  select * into v_invitation
  from public.organization_invitations invitation
  where invitation.id = p_invitation_id
    and invitation.organization_id = p_organization_id
  for update;
  if not found then
    raise sqlstate 'KX404' using message = 'Invitation not found';
  end if;
  if v_invitation.accepted_at is not null then
    raise sqlstate 'KX409' using message = 'An accepted invitation cannot be revoked';
  end if;

  insert into public.idempotency_keys (
    organization_id, user_id, key, operation, request_hash
  ) values (
    p_organization_id, v_user_id, p_idempotency_key, v_operation, p_request_hash
  );
  if v_invitation.revoked_at is null then
    update public.organization_invitations
    set revoked_at = v_now, revoked_by = v_user_id
    where id = p_invitation_id;
    insert into public.audit_events (
      organization_id, actor_user_id, action, target_type, target_id,
      request_id, metadata, created_at
    ) values (
      p_organization_id, v_user_id, 'organization.invitation.revoked',
      'organization_invitation', p_invitation_id::text, p_idempotency_key,
      jsonb_build_object('role', v_invitation.role), v_now
    );
  end if;
  v_response := jsonb_build_object(
    'status', 'revoked',
    'invitationId', p_invitation_id,
    'replayed', false
  );
  update public.idempotency_keys
  set response_body = v_response, response_status = 200, completed_at = v_now
  where organization_id = p_organization_id
    and user_id = v_user_id
    and key = p_idempotency_key;
  return v_response;
end;
$$;

revoke all on function public.revoke_kingxford_organization_invitation(
  uuid, uuid, text, text
) from public;
grant execute on function public.revoke_kingxford_organization_invitation(
  uuid, uuid, text, text
) to authenticated;

create or replace function public.manage_kingxford_organization_member(
  p_organization_id uuid,
  p_target_user_id uuid,
  p_action text,
  p_role public.organization_role,
  p_idempotency_key text,
  p_request_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_actor_role public.organization_role;
  v_target_role public.organization_role;
  v_operation constant text := 'organization.member.manage';
  v_previous public.idempotency_keys%rowtype;
  v_response jsonb;
  v_now timestamptz := now();
  v_owner_count bigint;
  v_replacement_owner uuid;
begin
  if v_user_id is null then
    raise sqlstate 'KX401' using message = 'Authentication required';
  end if;
  select membership.role into v_actor_role
  from public.organization_members membership
  where membership.organization_id = p_organization_id
    and membership.user_id = v_user_id;
  if v_actor_role is null or v_actor_role not in ('owner', 'admin') then
    raise sqlstate 'KX403' using message = 'Only organization owners and administrators can manage members';
  end if;
  if p_action not in ('update', 'remove')
    or (p_action = 'update' and p_role is null)
    or (p_action = 'remove' and p_role is not null)
    or char_length(p_idempotency_key) not between 8 and 160
    or p_request_hash !~ '^kxhash_[0-9a-f]{32}$' then
    raise sqlstate 'KX400' using message = 'Invalid member change';
  end if;
  if p_target_user_id = v_user_id then
    raise sqlstate 'KX403' using message = 'Use account controls for your own membership; another owner must change an administrative role';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      p_organization_id::text || ':' || v_user_id::text || ':' || p_idempotency_key,
      0
    )
  );
  select * into v_previous
  from public.idempotency_keys key_record
  where key_record.organization_id = p_organization_id
    and key_record.user_id = v_user_id
    and key_record.key = p_idempotency_key
  for update;
  if found then
    if v_previous.operation <> v_operation or v_previous.request_hash <> p_request_hash then
      raise sqlstate 'KX409' using message = 'Idempotency key conflict';
    end if;
    return v_previous.response_body || jsonb_build_object('replayed', true);
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_organization_id::text || ':membership', 0)
  );
  select membership.role into v_target_role
  from public.organization_members membership
  where membership.organization_id = p_organization_id
    and membership.user_id = p_target_user_id
  for update;
  if v_target_role is null then
    raise sqlstate 'KX404' using message = 'Organization member not found';
  end if;
  if v_actor_role = 'admin' and (v_target_role = 'owner' or p_role = 'owner') then
    raise sqlstate 'KX403' using message = 'Only an owner can change organization ownership';
  end if;
  if p_role = 'owner' and v_actor_role <> 'owner' then
    raise sqlstate 'KX403' using message = 'Only an owner can appoint another owner';
  end if;

  select count(*) into v_owner_count
  from public.organization_members membership
  where membership.organization_id = p_organization_id
    and membership.role = 'owner';
  if v_target_role = 'owner'
    and (p_action = 'remove' or p_role <> 'owner')
    and v_owner_count <= 1 then
    raise sqlstate 'KX409' using message = 'The sole organization owner cannot be removed or demoted';
  end if;

  insert into public.idempotency_keys (
    organization_id, user_id, key, operation, request_hash
  ) values (
    p_organization_id, v_user_id, p_idempotency_key, v_operation, p_request_hash
  );

  if p_action = 'update' then
    update public.organization_members
    set role = p_role
    where organization_id = p_organization_id and user_id = p_target_user_id;
    v_response := jsonb_build_object(
      'status', 'updated', 'userId', p_target_user_id,
      'role', p_role, 'replayed', false
    );
  else
    delete from public.organization_members
    where organization_id = p_organization_id and user_id = p_target_user_id;
    v_response := jsonb_build_object(
      'status', 'removed', 'userId', p_target_user_id,
      'role', null, 'replayed', false
    );
  end if;

  if v_target_role = 'owner'
    and (p_action = 'remove' or p_role <> 'owner')
    and exists (
      select 1 from public.organizations organization
      where organization.id = p_organization_id
        and organization.owner_user_id = p_target_user_id
    ) then
    select membership.user_id into v_replacement_owner
    from public.organization_members membership
    where membership.organization_id = p_organization_id
      and membership.role = 'owner'
      and membership.user_id <> p_target_user_id
    order by membership.joined_at, membership.user_id
    limit 1;
    update public.organizations
    set owner_user_id = v_replacement_owner
    where id = p_organization_id;
  end if;

  insert into public.audit_events (
    organization_id, actor_user_id, action, target_type, target_id,
    request_id, metadata, created_at
  ) values (
    p_organization_id, v_user_id,
    case when p_action = 'remove'
      then 'organization.member.removed'
      else 'organization.member.role_updated'
    end,
    'organization_member', p_target_user_id::text, p_idempotency_key,
    jsonb_build_object('previousRole', v_target_role, 'role', p_role), v_now
  );
  update public.idempotency_keys
  set response_body = v_response, response_status = 200, completed_at = v_now
  where organization_id = p_organization_id
    and user_id = v_user_id
    and key = p_idempotency_key;
  return v_response;
end;
$$;

revoke all on function public.manage_kingxford_organization_member(
  uuid, uuid, text, public.organization_role, text, text
) from public;
grant execute on function public.manage_kingxford_organization_member(
  uuid, uuid, text, public.organization_role, text, text
) to authenticated;

create or replace function public.accept_kingxford_organization_invitation(
  p_token_hash text,
  p_idempotency_key text,
  p_request_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_user_email text;
  v_operation constant text := 'organization.invitation.accept';
  v_invitation public.organization_invitations%rowtype;
  v_previous public.idempotency_keys%rowtype;
  v_existing_role public.organization_role;
  v_organization_name text;
  v_response jsonb;
  v_now timestamptz := now();
begin
  if v_user_id is null then
    raise sqlstate 'KX401' using message = 'Authentication required';
  end if;
  if p_token_hash !~ '^[0-9a-f]{64}$'
    or char_length(p_idempotency_key) not between 8 and 160
    or p_request_hash !~ '^kxhash_[0-9a-f]{32}$' then
    raise sqlstate 'KX400' using message = 'Invalid invitation acceptance';
  end if;

  select lower(trim(user_record.email)) into v_user_email
  from auth.users user_record
  where user_record.id = v_user_id;
  if v_user_email is null then
    raise sqlstate 'KX403' using message = 'A verified account email is required to accept this invitation';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('kingxford-invitation:' || p_token_hash, 0)
  );
  select * into v_invitation
  from public.organization_invitations invitation
  where invitation.token_hash = p_token_hash
  for update;
  if not found then
    raise sqlstate 'KX404' using message = 'Invitation not found';
  end if;
  if v_invitation.email <> v_user_email then
    raise sqlstate 'KX403' using message = 'This invitation was issued to a different account email';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      v_invitation.organization_id::text || ':' || v_user_id::text || ':' || p_idempotency_key,
      0
    )
  );
  select * into v_previous
  from public.idempotency_keys key_record
  where key_record.organization_id = v_invitation.organization_id
    and key_record.user_id = v_user_id
    and key_record.key = p_idempotency_key
  for update;
  if found then
    if v_previous.operation <> v_operation or v_previous.request_hash <> p_request_hash then
      raise sqlstate 'KX409' using message = 'Idempotency key conflict';
    end if;
    return v_previous.response_body || jsonb_build_object('replayed', true);
  end if;

  if v_invitation.accepted_at is not null then
    raise sqlstate 'KX410' using message = 'This invitation has already been used';
  end if;
  if v_invitation.revoked_at is not null then
    raise sqlstate 'KX410' using message = 'This invitation has been revoked';
  end if;
  if v_invitation.expires_at <= v_now then
    raise sqlstate 'KX410' using message = 'This invitation has expired';
  end if;

  insert into public.idempotency_keys (
    organization_id, user_id, key, operation, request_hash
  ) values (
    v_invitation.organization_id, v_user_id, p_idempotency_key,
    v_operation, p_request_hash
  );

  select membership.role into v_existing_role
  from public.organization_members membership
  where membership.organization_id = v_invitation.organization_id
    and membership.user_id = v_user_id
  for update;
  if v_existing_role is null then
    insert into public.organization_members (organization_id, user_id, role, joined_at)
    values (v_invitation.organization_id, v_user_id, v_invitation.role, v_now);
  end if;
  update public.organization_invitations
  set accepted_by = v_user_id, accepted_at = v_now
  where id = v_invitation.id;

  select organization.name into v_organization_name
  from public.organizations organization
  where organization.id = v_invitation.organization_id;
  insert into public.audit_events (
    organization_id, actor_user_id, action, target_type, target_id,
    request_id, metadata, created_at
  ) values (
    v_invitation.organization_id, v_user_id, 'organization.invitation.accepted',
    'organization_invitation', v_invitation.id::text, p_idempotency_key,
    jsonb_build_object(
      'role', coalesce(v_existing_role, v_invitation.role),
      'existingMember', v_existing_role is not null
    ), v_now
  );
  v_response := jsonb_build_object(
    'status', case when v_existing_role is null then 'accepted' else 'already_member' end,
    'organizationId', v_invitation.organization_id,
    'organizationName', v_organization_name,
    'role', coalesce(v_existing_role, v_invitation.role),
    'replayed', false
  );
  update public.idempotency_keys
  set response_body = v_response, response_status = 200, completed_at = v_now
  where organization_id = v_invitation.organization_id
    and user_id = v_user_id
    and key = p_idempotency_key;
  return v_response;
end;
$$;

revoke all on function public.accept_kingxford_organization_invitation(
  text, text, text
) from public;
grant execute on function public.accept_kingxford_organization_invitation(
  text, text, text
) to authenticated;

-- Account deletion receipts are intentionally not tied to an organization
-- foreign key: they survive organization deletion long enough to make a lost
-- response safely replayable, then can be purged by routine retention work.
create table if not exists public.cloud_account_deletion_receipts (
  user_id uuid not null references auth.users(id) on delete cascade,
  idempotency_key text not null check (char_length(idempotency_key) between 8 and 160),
  organization_id uuid not null,
  request_hash text not null check (request_hash ~ '^kxhash_[0-9a-f]{32}$'),
  response_body jsonb not null check (jsonb_typeof(response_body) = 'object'),
  created_at timestamptz not null default now(),
  primary key (user_id, idempotency_key)
);

create index if not exists cloud_account_deletion_receipts_expiry_idx
  on public.cloud_account_deletion_receipts(created_at);
alter table public.cloud_account_deletion_receipts enable row level security;
revoke all on public.cloud_account_deletion_receipts from authenticated;

create or replace function public.replay_kingxford_cloud_data_deletion(
  p_organization_id uuid,
  p_idempotency_key text,
  p_request_hash text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_receipt public.cloud_account_deletion_receipts%rowtype;
begin
  if v_user_id is null then
    raise sqlstate 'KX401' using message = 'Authentication required';
  end if;
  if char_length(p_idempotency_key) not between 8 and 160
    or p_request_hash !~ '^kxhash_[0-9a-f]{32}$' then
    raise sqlstate 'KX400' using message = 'Invalid deletion replay request';
  end if;
  select * into v_receipt
  from public.cloud_account_deletion_receipts receipt
  where receipt.user_id = v_user_id
    and receipt.idempotency_key = p_idempotency_key;
  if not found then
    return null;
  end if;
  if v_receipt.organization_id <> p_organization_id
    or v_receipt.request_hash <> p_request_hash then
    raise sqlstate 'KX409' using message = 'Idempotency key conflict';
  end if;
  return v_receipt.response_body || jsonb_build_object('replayed', true);
end;
$$;

revoke all on function public.replay_kingxford_cloud_data_deletion(
  uuid, text, text
) from public;
grant execute on function public.replay_kingxford_cloud_data_deletion(
  uuid, text, text
) to authenticated;

create or replace function public.delete_my_kingxford_cloud_data(
  p_organization_id uuid,
  p_idempotency_key text,
  p_request_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_role public.organization_role;
  v_member_count bigint;
  v_receipt public.cloud_account_deletion_receipts%rowtype;
  v_response jsonb;
  v_storage_paths jsonb := '[]'::jsonb;
begin
  if v_user_id is null then
    raise sqlstate 'KX401' using message = 'Authentication required';
  end if;
  if char_length(p_idempotency_key) not between 8 and 160
    or p_request_hash !~ '^kxhash_[0-9a-f]{32}$' then
    raise sqlstate 'KX400' using message = 'Invalid deletion request';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'kingxford-account-delete:' || v_user_id::text || ':' || p_idempotency_key,
      0
    )
  );
  select * into v_receipt
  from public.cloud_account_deletion_receipts receipt
  where receipt.user_id = v_user_id
    and receipt.idempotency_key = p_idempotency_key
  for update;
  if found then
    if v_receipt.organization_id <> p_organization_id
      or v_receipt.request_hash <> p_request_hash then
      raise sqlstate 'KX409' using message = 'Idempotency key conflict';
    end if;
    return v_receipt.response_body || jsonb_build_object('replayed', true);
  end if;

  select membership.role into v_role
  from public.organization_members membership
  where membership.organization_id = p_organization_id
    and membership.user_id = v_user_id
  for update;
  if v_role is null then
    raise sqlstate 'KX403' using message = 'Organization access denied';
  end if;

  select count(*) into v_member_count
  from public.organization_members membership
  where membership.organization_id = p_organization_id;
  if v_role = 'owner' and v_member_count > 1 then
    raise sqlstate 'KX403' using message = 'Transfer organization ownership before deleting personal cloud access';
  end if;

  if v_role = 'owner' then
    select coalesce(
      jsonb_agg(evidence.storage_path order by evidence.storage_path),
      '[]'::jsonb
    ) into v_storage_paths
    from public.evidence_objects evidence
    where evidence.organization_id = p_organization_id;
    v_response := jsonb_build_object(
      'organizationDeleted', true,
      'organizationId', p_organization_id,
      'authIdentityDeleted', false,
      'storagePaths', v_storage_paths,
      'replayed', false
    );
    delete from public.organizations where id = p_organization_id;
  else
    v_response := jsonb_build_object(
      'organizationDeleted', false,
      'membershipDeleted', true,
      'organizationId', p_organization_id,
      'authIdentityDeleted', false,
      'storagePaths', '[]'::jsonb,
      'replayed', false
    );
    delete from public.usage_records
    where organization_id = p_organization_id and user_id = v_user_id;
    delete from public.organization_members
    where organization_id = p_organization_id and user_id = v_user_id;
  end if;

  insert into public.cloud_account_deletion_receipts (
    user_id, idempotency_key, organization_id, request_hash, response_body
  ) values (
    v_user_id, p_idempotency_key, p_organization_id, p_request_hash, v_response
  );
  return v_response;
end;
$$;

revoke all on function public.delete_my_kingxford_cloud_data(
  uuid, text, text
) from public;
grant execute on function public.delete_my_kingxford_cloud_data(
  uuid, text, text
) to authenticated;
